server {
    listen 8080;
    
    server_name ${CORP_DOMAIN};

    location / {
        proxy_pass https://web.telegram.org;

        proxy_ssl_server_name on;
        proxy_ssl_name web.telegram.org;

        proxy_ssl_protocols TLSv1.3;
        proxy_ssl_ciphers 'ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384';

        proxy_ssl_verify on;
        proxy_ssl_verify_depth 2;
        proxy_ssl_trusted_certificate /etc/ssl/certs/ca-certificates.crt;

        proxy_set_header Host web.telegram.org;
        proxy_set_header User-Agent "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36";
        proxy_set_header Accept "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8";
        proxy_set_header Accept-Language "ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7";
        proxy_set_header Accept-Encoding "gzip, deflate, br";
        proxy_set_header Cache-Control "no-cache";
        proxy_set_header Sec-Fetch-Dest "document";
        proxy_set_header Sec-Fetch-Mode "navigate";
        proxy_set_header Sec-Fetch-Site "none";

        proxy_set_header X-Forwarded-For "";
        proxy_set_header X-Real-IP "";
        proxy_set_header X-Forwarded-Proto "";
        proxy_set_header Via "";

        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        proxy_buffering off;
        proxy_read_timeout 3600s;
        proxy_send_timeout 3600s;

        proxy_buffer_size 128k;
        proxy_buffers 4 256k;
        proxy_busy_buffers_size 256k;
    }
}